# Site settings
title: TensorFlow User Group Kolkata
email: tfugkol@gmail.com
description: >
  TensorFlow User Group (TFUG) Kolkata is a local community for developers, researchers, users, and writers interested in ML. TFUG Kolkata's meetups are composed of events around ML and TF to share best practices, discuss the future technology road-map, upcoming features, technology pitfalls and the entire gamut of Googleâ€™s TF related panoramic technology landscape.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://tfugkol.github.io"
twitter_username: TFUGKol
github_username:  tfugkol
facebook_username: TFUGKol
permalink: /:title/

# Layout settings
header_type: default  # values [ drawer, default ]
post_type: highlight    # values [ highlight, default ]
pagination_type: default  # values [ ops, default ]

more_vert:
  option1:
    name: Feedback
    link: /feedback
  option2:
    name: View on GitHub
    link: https://github.com/tfugkol/tfugkol.github.io

disqus: true
disqus_shortname: 'tfugkol'

# Build settings
markdown: kramdown

exclude: [CHANGELOG.md, LICENSE, README.md, Gemfile, Gemfile.lock]